package:
  name: {{ FastK }}
  version: {{ 1.0.0 }}
source:
  url: https://github.com/Kujahjos/FASTK
  sha256: s3_sign(unsigned char *digest, kstring_t *key, kstring_t *message)
build:
skip: true 
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - FASTK
    - FASTK.tests
  requires:
    - pip
  commands:
    - pip check
about:
  home: https://github.com/Kujahjos/FASTK
  license: MIT
  license_family: MIT
  license_file: LICENSE_FastK
  summary: A fast K-mer counter for high-fidelity shotgun datasets
  description: |
    FastK is a k‑mer counter that is optimized for processing high quality 
    DNA assembly data sets such as those produced with an Illumina instrument 
    or a PacBio run in HiFi mode. For example it is about 2 times faster than 
    KMC3 when counting 40-mers in a 50X HiFi data set. Its relative speedup 
    decreases with increasing error rate or increasing values of k, but 
    regardless is a general program that works for any DNA sequence data set and 
    choice of k. It is further designed to handle data sets of arbitrarily large size, 
    e.g. a 100X data set of a 32GB Axolotl genome (3.2Tbp) can be performed on a 
    machine with just 12GB of memory provided it has ~6.5TB of disk space available.
  doc_url: https://github.com/Kujahjos/FASTK
  dev_url: https://github.com/Kujahjos/FASTK/blob/master/README.md

extra:
  recipe-maintainers:
    -Kujahjos                                                    
  
